spring.datasource.url=jdbc:mysql://localhost:3306/barberia_bd
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.devtools.restart.exclude=uploads/**
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ─────────────────────────────────────────────────
# TWILIO — WhatsApp
# Crea tu cuenta gratis en: https://www.twilio.com
# ─────────────────────────────────────────────────
twilio.account.sid=ACef6acfb95c83ebafafd8474ae3638220
twilio.auth.token=fd2e81269d315050bedcf38dd1f1e0b9
# En sandbox de Twilio el número es siempre este:
twilio.whatsapp.from=whatsapp:+14155238886
 
# ─────────────────────────────────────────────────
# SUBIDA DE COMPROBANTES
# Carpeta donde se guardarán las imágenes de Yape
# ─────────────────────────────────────────────────
app.upload.dir=uploads/comprobantes
