spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.devtools.restart.exclude=uploads/**
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuración de Servidor de Correo
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=${MAIL_PORT}
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
app.mail.from=Barbería La Clásica <${MAIL_USER}>
app.upload.dir=uploads/comprobantes
api.dni.token=${API_DNI_TOKEN}
